#!/bin/bash

set -e

# Finder sidebar size
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# Tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Dock settings
defaults write com.apple.dock tilesize -int 36
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide -bool true

# set vim key repeat in vscode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

for app in "Dock" "Finder"; do
  killall "${app}" > /dev/null 2>&1
done

