#!/bin/bash

set -e

curl -s "https://get.sdkman.io" | bash

# set vim key repeat in vscode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# Finder sidebar size
defaults write NSGlobalDomain NSTableViewDefaultSizeMode -int 1

# Tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Dock settings
defaults write com.apple.dock tilesize -int 36
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock autohide -bool true

for app in "Dock" "Finder"; do
  killall "${app}" > /dev/null 2>&1
done

printf "\n\e[1mDone.\e[0m\n"
echo "Note that some of these changes require a logout/restart of your OS to take effect.  At a minimum, be sure to restart your Terminal."
