#!/bin/bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `install.sh` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

./scripts/setup-mac
./scripts/setup-vim
./scripts/setup-zsh
./scripts/setup-git
./scripts/setup-ssh
./scripts/setup-tmux
./scripts/setup-homebrew
