#!/bin/bash

set -e

source './setup-helpers'

# brew install vim

mkdir -p ~/.vim/autoload ~/.vim/bundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

install_dotfile "vimrc"

vim +PluginInstall +qall
