#!/bin/sh

if test ! $(which brew); then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

brew update
brew upgrade --all

# Install packages
brew install hub
brew install node
brew install tmux
brew install jq
brew install yarn
brew install vlc

# Install casks
brew cask install --appdir="/Applications" visual-studio-code
brew cask install --appdir="/Applications" google-chrome
brew cask install --appdir="/Applications" brave-browser
brew cask install --appdir="/Applications" slack
brew cask install --appdir="/Applications" obs
brew cask install --appdir="/Applications" iterm2
brew cask install --appdir="/Applications" spotify

brew cleanup
