#!/bin/sh

set -e

if test ! $(which zsh); then
  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

source './setup-helpers'

git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh

install_dotfile "oh-my-zsh/themes/john.zsh-theme"
install_dotfile "zshrc"
install_dotfile "zsh_functions"
install_dotfile "zsh_aliases"
